// AUTO-GENERATED BY LocalisationCodegen - DO NOT EDIT BY HAND
// Generated at: 2025-12-16 12:43:39

namespace Core.Localisation
{
    public static class defs
    {
        // No canonical lang_<id>.yaml found. Create at least one file (e.g. lang_en.yaml) and regenerate.
    }
}
