// AUTO-GENERATED BY LocalisationCodegen - DO NOT EDIT BY HAND
// Generated at: 2025-12-16 12:43:39

namespace Core.Localisation
{
    public static class langs
    {
        // No lang_<id>.yaml files found under Assets/Core/Data/localisation
    }
}
