// AUTO-GENERATED BY StringEnumLibrary - DO NOT EDIT BY HAND
// Source asset: Assets/Enums.asset
// Generated at: 2025-12-16 08:30:36

namespace Core.Enums
{
    public static class Ammo
    {
        public static readonly SerialEnum emp = new SerialEnum("Ammo.emp");
        public static readonly SerialEnum explosive = new SerialEnum("Ammo.explosive");
        public static readonly SerialEnum large = new SerialEnum("Ammo.large");
        public static readonly SerialEnum medium = new SerialEnum("Ammo.medium");
        public static readonly SerialEnum small = new SerialEnum("Ammo.small");
    }

    public static class Rarity
    {
        public static readonly SerialEnum common = new SerialEnum("Rarity.common");
        public static readonly SerialEnum epic = new SerialEnum("Rarity.epic");
        public static readonly SerialEnum exhalted = new SerialEnum("Rarity.exhalted");
        public static readonly SerialEnum legendary = new SerialEnum("Rarity.legendary");
        public static readonly SerialEnum rare = new SerialEnum("Rarity.rare");
        public static readonly SerialEnum trash = new SerialEnum("Rarity.trash");
        public static readonly SerialEnum uncommon = new SerialEnum("Rarity.uncommon");
    }

}
